server.port=8081

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate

logging.level.root=INFO
logging.level.com.ht_rnd.wifi_admin_service=INFO
logging.level.org.springframework.ws.client.MessageTracing=INFO

wifi.sync.enabled=true
wifi.sync.initial-delay-ms=60000
wifi.sync.fixed-delay-ms=300000

management.endpoints.web.base-path=/actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when_authorized

app.security.username=${APP_SECURITY_USERNAME}
app.security.password=${APP_SECURITY_PASSWORD}