spring.application.name=wifi-admin-service
spring.profiles.active=dev

# Common JPA
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update

# Scheduler defaults
wifi.sync.enabled=true
wifi.sync.initial-delay-ms=10000
wifi.sync.fixed-delay-ms=60000

# Logging
logging.level.root=INFO
logging.level.com.ht_rnd.wifi_admin_service=INFO
logging.level.org.springframework.ws.client.MessageTracing=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n
logging.file.name=logs/wifi-admin-service.log

# Actuator
management.endpoints.web.base-path=/actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when_authorized
management.endpoint.info.access=read_only

# Security defaults
app.security.username=admin
app.security.password=admin123