spring.application.name=wifi-admin-service
server.port=8081
soap.endpoint.url=http://localhost:8080/platform


logging.level.org.springframework.ws.client.MessageTracing.received=TRACE
logging.level.org.springframework.ws.client.MessageTracing.sent=TRACE