server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/wifi_admin_db
spring.datasource.username=wifi_admin_user
spring.datasource.password=wifi_admin_user

logging.level.com.ht_rnd.wifi_admin_service=DEBUG
logging.level.org.springframework.ws.client.MessageTracing=TRACE

wifi.sync.enabled=true
wifi.sync.initial-delay-ms=10000
wifi.sync.fixed-delay-ms=30000

app.security.username=admin
app.security.password=admin123